
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int BIT_XOR = 53;
  public static final int WHEN = 22;
  public static final int RIGHT_RBRACKET = 61;
  public static final int PLUS_ASSIGN = 45;
  public static final int ELSIF = 25;
  public static final int ID_ITER = 5;
  public static final int BIT_NOT = 54;
  public static final int BIT_AND = 51;
  public static final int NOT_EQUAL = 39;
  public static final int CASE = 21;
  public static final int RIGHT_SBRACKET = 63;
  public static final int GREATER = 40;
  public static final int INT = 6;
  public static final int LESS = 41;
  public static final int FOR = 15;
  public static final int MINUS = 33;
  public static final int ID_GLOBAL = 3;
  public static final int NOT = 59;
  public static final int AND = 57;
  public static final int SEMICOLON = 12;
  public static final int NIL = 8;
  public static final int OR = 58;
  public static final int COMMA = 10;
  public static final int DIV = 35;
  public static final int LESS_EQUAL = 42;
  public static final int PLUS = 32;
  public static final int ASSIGN = 44;
  public static final int IF = 20;
  public static final int EXP = 37;
  public static final int LEFT_RBRACKET = 60;
  public static final int DOT = 11;
  public static final int ID = 2;
  public static final int RETRY = 28;
  public static final int CRLF = 13;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int ID_FUNCTION = 4;
  public static final int EQUAL = 38;
  public static final int GREATER_EQUAL = 43;
  public static final int TRUE = 30;
  public static final int error = 1;
  public static final int LEFT_SBRACKET = 62;
  public static final int MUL = 34;
  public static final int MOD = 36;
  public static final int REQUIRE = 16;
  public static final int BREAK = 29;
  public static final int MOD_ASSIGN = 49;
  public static final int DIV_ASSIGN = 48;
  public static final int LITERAL = 9;
  public static final int ELSE = 24;
  public static final int EXP_ASSIGN = 50;
  public static final int WHILE = 27;
  public static final int UNLESS = 26;
  public static final int FLOAT = 7;
  public static final int THEN = 23;
  public static final int END = 17;
  public static final int MUL_ASSIGN = 47;
  public static final int DEF = 18;
  public static final int BIT_SHR = 56;
  public static final int BIT_OR = 52;
  public static final int FALSE = 31;
  public static final int BIT_SHL = 55;
  public static final int MINUS_ASSIGN = 46;
  public static final int DO = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "ID_GLOBAL",
  "ID_FUNCTION",
  "ID_ITER",
  "INT",
  "FLOAT",
  "NIL",
  "LITERAL",
  "COMMA",
  "DOT",
  "SEMICOLON",
  "CRLF",
  "DO",
  "FOR",
  "REQUIRE",
  "END",
  "DEF",
  "RETURN",
  "IF",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "ELSIF",
  "UNLESS",
  "WHILE",
  "RETRY",
  "BREAK",
  "TRUE",
  "FALSE",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "EXP",
  "EQUAL",
  "NOT_EQUAL",
  "GREATER",
  "LESS",
  "LESS_EQUAL",
  "GREATER_EQUAL",
  "ASSIGN",
  "PLUS_ASSIGN",
  "MINUS_ASSIGN",
  "MUL_ASSIGN",
  "DIV_ASSIGN",
  "MOD_ASSIGN",
  "EXP_ASSIGN",
  "BIT_AND",
  "BIT_OR",
  "BIT_XOR",
  "BIT_NOT",
  "BIT_SHL",
  "BIT_SHR",
  "AND",
  "OR",
  "NOT",
  "LEFT_RBRACKET",
  "RIGHT_RBRACKET",
  "LEFT_SBRACKET",
  "RIGHT_SBRACKET"
  };
}

