
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 01 18:15:24 CEST 2017
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BIT_XOR = 50;
  public static final int WHEN = 19;
  public static final int RIGHT_RBRACKET = 58;
  public static final int PLUS_ASSIGN = 42;
  public static final int ELSIF = 22;
  public static final int ID_ITER = 5;
  public static final int BIT_NOT = 51;
  public static final int BIT_AND = 48;
  public static final int NOT_EQUAL = 36;
  public static final int CASE = 18;
  public static final int RIGHT_SBRACKET = 60;
  public static final int GREATER = 37;
  public static final int INT = 61;
  public static final int LESS = 38;
  public static final int MINUS = 30;
  public static final int ID_GLOBAL = 3;
  public static final int NOT = 56;
  public static final int AND = 54;
  public static final int SEMICOLON = 10;
  public static final int NIL = 7;
  public static final int OR = 55;
  public static final int COMMA = 8;
  public static final int DIV = 32;
  public static final int LESS_EQUAL = 39;
  public static final int PLUS = 29;
  public static final int ASSIGN = 41;
  public static final int IF = 17;
  public static final int EXP = 34;
  public static final int LEFT_RBRACKET = 57;
  public static final int DOT = 9;
  public static final int ID = 2;
  public static final int RETRY = 25;
  public static final int CRLF = 11;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int ID_FUNCTION = 4;
  public static final int EQUAL = 35;
  public static final int GREATER_EQUAL = 40;
  public static final int TRUE = 27;
  public static final int error = 1;
  public static final int LEFT_SBRACKET = 59;
  public static final int MUL = 31;
  public static final int REQUIRE = 13;
  public static final int MOD = 33;
  public static final int BREAK = 26;
  public static final int MOD_ASSIGN = 46;
  public static final int DIV_ASSIGN = 45;
  public static final int LITERAL = 62;
  public static final int ELSE = 21;
  public static final int EXP_ASSIGN = 47;
  public static final int WHILE = 24;
  public static final int UNLESS = 23;
  public static final int FLOAT = 6;
  public static final int THEN = 20;
  public static final int END = 14;
  public static final int MUL_ASSIGN = 44;
  public static final int DEF = 15;
  public static final int BIT_SHR = 53;
  public static final int BIT_OR = 49;
  public static final int FALSE = 28;
  public static final int BIT_SHL = 52;
  public static final int MINUS_ASSIGN = 43;
  public static final int DO = 12;
}

