
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 06 18:49:01 GMT 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BIT_XOR = 47;
  public static final int WHEN = 16;
  public static final int RIGHT_RBRACKET = 55;
  public static final int PLUS_ASSIGN = 39;
  public static final int ELSIF = 19;
  public static final int BIT_NOT = 48;
  public static final int BIT_AND = 45;
  public static final int CASE = 15;
  public static final int NOT_EQUAL = 33;
  public static final int RIGHT_SBRACKET = 57;
  public static final int GREATER = 34;
  public static final int INT = 59;
  public static final int LESS = 35;
  public static final int MINUS = 27;
  public static final int ID_GLOBAL = 3;
  public static final int NOT = 53;
  public static final int AND = 51;
  public static final int SEMICOLON = 8;
  public static final int NIL = 58;
  public static final int OR = 52;
  public static final int COMMA = 6;
  public static final int DIV = 29;
  public static final int LESS_EQUAL = 36;
  public static final int PLUS = 26;
  public static final int ASSIGN = 38;
  public static final int IF = 14;
  public static final int EXP = 31;
  public static final int LEFT_RBRACKET = 54;
  public static final int DOT = 7;
  public static final int ID = 2;
  public static final int RETRY = 22;
  public static final int CRLF = 9;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int ID_FUNCTION = 4;
  public static final int EQUAL = 32;
  public static final int GREATER_EQUAL = 37;
  public static final int TRUE = 24;
  public static final int error = 1;
  public static final int LEFT_SBRACKET = 56;
  public static final int MUL = 28;
  public static final int REQUIRE = 10;
  public static final int MOD = 30;
  public static final int BREAK = 23;
  public static final int MOD_ASSIGN = 43;
  public static final int DIV_ASSIGN = 42;
  public static final int LITERAL = 60;
  public static final int ELSE = 18;
  public static final int EXP_ASSIGN = 44;
  public static final int WHILE = 21;
  public static final int UNLESS = 20;
  public static final int FLOAT = 5;
  public static final int THEN = 17;
  public static final int END = 11;
  public static final int MUL_ASSIGN = 41;
  public static final int DEF = 12;
  public static final int BIT_SHR = 50;
  public static final int BIT_OR = 46;
  public static final int FALSE = 25;
  public static final int BIT_SHL = 49;
  public static final int MINUS_ASSIGN = 40;
}

