
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 05 18:47:20 CEST 2017
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BIT_XOR = 45;
  public static final int WHEN = 14;
  public static final int RIGHT_RBRACKET = 53;
  public static final int PLUS_ASSIGN = 37;
  public static final int ID_ITER = 59;
  public static final int ELSIF = 17;
  public static final int BIT_NOT = 46;
  public static final int BIT_AND = 43;
  public static final int CASE = 13;
  public static final int NOT_EQUAL = 31;
  public static final int RIGHT_SBRACKET = 55;
  public static final int GREATER = 32;
  public static final int INT = 61;
  public static final int LESS = 33;
  public static final int MINUS = 25;
  public static final int ID_GLOBAL = 57;
  public static final int NOT = 51;
  public static final int AND = 49;
  public static final int SEMICOLON = 5;
  public static final int NIL = 60;
  public static final int OR = 50;
  public static final int COMMA = 3;
  public static final int DIV = 27;
  public static final int LESS_EQUAL = 34;
  public static final int PLUS = 24;
  public static final int ASSIGN = 36;
  public static final int IF = 12;
  public static final int EXP = 29;
  public static final int ID = 56;
  public static final int LEFT_RBRACKET = 52;
  public static final int DOT = 4;
  public static final int RETRY = 20;
  public static final int CRLF = 6;
  public static final int EOF = 0;
  public static final int ID_FUNCTION = 58;
  public static final int RETURN = 11;
  public static final int EQUAL = 30;
  public static final int GREATER_EQUAL = 35;
  public static final int TRUE = 22;
  public static final int error = 1;
  public static final int LEFT_SBRACKET = 54;
  public static final int MUL = 26;
  public static final int REQUIRE = 8;
  public static final int MOD = 28;
  public static final int BREAK = 21;
  public static final int MOD_ASSIGN = 41;
  public static final int DIV_ASSIGN = 40;
  public static final int LITERAL = 62;
  public static final int ELSE = 16;
  public static final int EXP_ASSIGN = 42;
  public static final int WHILE = 19;
  public static final int UNLESS = 18;
  public static final int FLOAT = 2;
  public static final int THEN = 15;
  public static final int END = 9;
  public static final int MUL_ASSIGN = 39;
  public static final int DEF = 10;
  public static final int BIT_SHR = 48;
  public static final int BIT_OR = 44;
  public static final int FALSE = 23;
  public static final int BIT_SHL = 47;
  public static final int MINUS_ASSIGN = 38;
  public static final int DO = 7;
}

